version: "3.1"
services:
  whiteboard:
    image: docker.pkg.github.com/purpleview/whiteboard/purpleview-whiteboard:latest
    restart: on-failure
    ports:
      - "8080:8080/tcp"
    command: --config=./config.default.yml
    volumes:
      - ./data/uploads:/opt/app/public/uploads"
      - ./data/savedBoards:/opt/app/savedBoards"
