# This workflow will do clean build of the docker image

name: Build and publish Whiteboard

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - "**"
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: purpleview-whiteboard

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          IMAGE_ID=docker.pkg.github.com/purpleview/whiteboard/$IMAGE_NAME
          VERSION=$(echo ${{ github.ref_name }} | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          docker build . --build-arg DOCKER_TAG=$VERSION --tag image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }} (Revision ${{ github.run_number }})
          draft: false
          prerelease: false

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate SBOM (CycloneDX JSON) from Docker image
        uses: anchore/sbom-action@v0
        id: extract-sbom-json
        with:
          image: ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          format: cyclonedx-json
          output-file: cyclonedx-bom-${{ env.VERSION }}.json

      - name: Save tag name to env
        run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
